CC = g++
CC_FLAGS = -std=c++17

all: part_one part_two

part_one:
	$(CC) $(CC_FLAGS) part_one.cc -o part_one

part_two:
	$(CC) $(CC_FLAGS) part_two.cc -o part_two

.PHONY: clean
clean:
	rm -rf *.o part_one part_two
