CC = g++

all: count_increases count_window_increases

count_increases:
	$(CC) count_increases.cc -o count_increases

count_window_increases:
	$(CC) count_window_increases.cc -o count_window_increases

.PHONY: clean
clean:
	rm -rf *.o count_increases count_window_increases
